# auto: true
source: ./_source


markdown: rdiscount
permalink: /:categories/:title
rdiscount extensions: [smart]


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      section_header: "false"