# auto: true
markdown: rdiscount
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
name: Frank Massi (@fdm1)

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"