# auto: true
markdown: rdiscount
permalink: /:categories/:title
rdiscount extensions: [smart]
name: Frank Massi (@fdm1)

resume_url: "https://github.com/fdm1/fdm1.github.io/blob/master/files/fdm_Resume_github.pdf?raw=true"
linkedin_url: "https://www.linkedin.com/in/frankmassi"
github_url: "https://github.com/fdm1/"

resume_button_text: "PDF Resume"
linkedin_button_text: "LinkedIn Profile"
github_button_text: "Github Profile"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
      section_header: "false"