#!/usr/bin/env ruby
make_this_branch = ARGV.first
origin = ARGV.last
origin = "master" if (origin == make_this_branch || origin.empty?)
new_branch = "#{make_this_branch}#{"_#{origin}" if origin != "master"}"

puts "creating Branch on local and Remote #{new_branch}"
puts `git pull`
puts `git checkout -b #{new_branch} #{origin}`
puts `git push origin #{new_branch}`
puts `git fetch`
puts `git branch -u origin/#{new_branch}`
